language: php

php:
  - 5.6
  - hhvm
  - nightly

sudo: false

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

